---
apiVersion: v1
kind: Template
metadata:
  name: drupal-deployment-job
  annotations:
    openshift.io/display-name: "Template for the Job that provisions the environment for each deployment of Drupal."
    description: "A Job that provisions the environment for each deployment of Drupal."
    iconClass: icon-drupal
labels:
  drupal-deployment-id: "${DEPLOYMENT_ID}"
parameters:
- name: DEPLOYMENT_ID
  description: "The id of Drupal deployment that we are executing this job for."
  displayName: "Deployment Id"
  required: true
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: drupal-deployment-job-${DEPLOYMENT_ID}
  spec:
    completions: 1
    backoffLimit: 1
    template:
      spec:
        restartPolicy: Never
        initContainers:
        - image: redhatdeveloper/rhdp-data-seed
          imagePullPolicy: IfNotPresent
          name: rhdp-data-seed
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          volumeMounts:
          - name: drupal-workspace
            mountPath: /drupal-workspace
        - image: redhatdeveloper/rhdp-drupal:${DEPLOYMENT_ID}
          imagePullPolicy: IfNotPresent
          name: rhdp-bootstrap-env
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          args: ['/usr/bin/ansible-playbook', '--vault-password-file=/credentials/ansible/password', '/ansible/bootstrap-env.yml']
          volumeMounts:
          - name: drupal-workspace
            mountPath: /drupal-workspace
          - name: ansible-vault
            mountPath: /credentials/ansible
        - image: redhatdeveloper/rhdp-drupal:${DEPLOYMENT_ID}
          imagePullPolicy: IfNotPresent
          name: rhdp-bootstrap-drupal
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          args: ['/usr/bin/ansible-playbook', '--vault-password-file=/credentials/ansible/password','/ansible/bootstrap-drupal.yml']
          volumeMounts:
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.yml
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.yml
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.php
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.php
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/files
            subPath: drupal_${DEPLOYMENT_ID}/drupal/files
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/config/active
            subPath: drupal_${DEPLOYMENT_ID}/drupal/config/active
          - name: ansible-vault
            mountPath: /credentials/ansible
        containers:
        - image: redhatdeveloper/rhdp-drupal:${DEPLOYMENT_ID}
          name: rhdp-env-create-complete
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "echo Bootstrap of environment for deployment '$DEPLOYMENT_ID' complete."]
        volumes:
        - name: drupal-workspace
          persistentVolumeClaim:
            claimName: drupal-workspace
        - name: ansible-vault
          secret:
            secretName: ansible-vault
            optional: false