apiVersion: v1
kind: Template
metadata:
  name: drupal-services
  annotations:
    openshift.io/display-name: "Creates all Services for a deployment of Drupal."
    description: "Creates alll Services for a deployment of Drupal."
    iconClass: icon-drupal
labels:
  drupal-deployment-id: "${DEPLOYMENT_ID}"
parameters:
- name: DEPLOYMENT_ID
  description: "The id of Drupal deployment that we are creating the services for."
  required: true
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: drupal-headless-${DEPLOYMENT_ID}
    labels:
      drupal-deployment-id: "${DEPLOYMENT_ID}"
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 8080
    clusterIP: None
    selector:
      drupal-deployment-id: "${DEPLOYMENT_ID}"
- kind: Service
  apiVersion: v1
  metadata:
    name: drupal-http-${DEPLOYMENT_ID}
    labels:
      drupal-deployment-id: "${DEPLOYMENT_ID}"
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 8080
    selector:
      drupal-deployment-id: ${DEPLOYMENT_ID}