apiVersion: v1
kind: Service
metadata:
  name: drupal-headless-2
  labels:
    drupal-deployment-id: "2"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    drupal-deployment-id: "2"